changelog:
  exclude:
    labels:
      - ignore-for-release
      - skip-changelog
  categories:
    - title: Features
      labels:
        - feature
        - enhancement
    - title: Fixes
      labels:
        - bug
        - fix
        - hotfix
    - title: Tests
      labels:
        - test
        - qa
    - title: Documentation
      labels:
        - documentation
    - title: Maintenance
      labels:
        - chore
        - dependencies